<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSRDUbdr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSRDUbdr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSRDUbdr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSRDUbdr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSRDUbdr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SRDUbdr',
    'container.build_id' => 'a4d843eb',
    'container.build_time' => 1610975949,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSRDUbdr');
